package com.cdx.domain.system;

public class Module {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.module_id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.parent_name
     *
     * @mbg.generated
     */
    private String parentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.layer_num
     *
     * @mbg.generated
     */
    private Long layerNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.is_leaf
     *
     * @mbg.generated
     */
    private Long isLeaf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.ico
     *
     * @mbg.generated
     */
    private String ico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.cpermission
     *
     * @mbg.generated
     */
    private String cpermission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.curl
     *
     * @mbg.generated
     */
    private String curl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.ctype
     *
     * @mbg.generated
     */
    private Long ctype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.state
     *
     * @mbg.generated
     */
    private Long state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.belong
     *
     * @mbg.generated
     */
    private String belong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.cwhich
     *
     * @mbg.generated
     */
    private String cwhich;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.quote_num
     *
     * @mbg.generated
     */
    private Long quoteNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.order_no
     *
     * @mbg.generated
     */
    private Long orderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.module_id
     *
     * @return the value of ss_module.module_id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.module_id
     *
     * @param id the value for ss_module.module_id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.parent_id
     *
     * @return the value of ss_module.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.parent_id
     *
     * @param parentId the value for ss_module.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.parent_name
     *
     * @return the value of ss_module.parent_name
     *
     * @mbg.generated
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.parent_name
     *
     * @param parentName the value for ss_module.parent_name
     *
     * @mbg.generated
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.name
     *
     * @return the value of ss_module.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.name
     *
     * @param name the value for ss_module.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.layer_num
     *
     * @return the value of ss_module.layer_num
     *
     * @mbg.generated
     */
    public Long getLayerNum() {
        return layerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.layer_num
     *
     * @param layerNum the value for ss_module.layer_num
     *
     * @mbg.generated
     */
    public void setLayerNum(Long layerNum) {
        this.layerNum = layerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.is_leaf
     *
     * @return the value of ss_module.is_leaf
     *
     * @mbg.generated
     */
    public Long getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.is_leaf
     *
     * @param isLeaf the value for ss_module.is_leaf
     *
     * @mbg.generated
     */
    public void setIsLeaf(Long isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.ico
     *
     * @return the value of ss_module.ico
     *
     * @mbg.generated
     */
    public String getIco() {
        return ico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.ico
     *
     * @param ico the value for ss_module.ico
     *
     * @mbg.generated
     */
    public void setIco(String ico) {
        this.ico = ico == null ? null : ico.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.cpermission
     *
     * @return the value of ss_module.cpermission
     *
     * @mbg.generated
     */
    public String getCpermission() {
        return cpermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.cpermission
     *
     * @param cpermission the value for ss_module.cpermission
     *
     * @mbg.generated
     */
    public void setCpermission(String cpermission) {
        this.cpermission = cpermission == null ? null : cpermission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.curl
     *
     * @return the value of ss_module.curl
     *
     * @mbg.generated
     */
    public String getCurl() {
        return curl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.curl
     *
     * @param curl the value for ss_module.curl
     *
     * @mbg.generated
     */
    public void setCurl(String curl) {
        this.curl = curl == null ? null : curl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.ctype
     *
     * @return the value of ss_module.ctype
     *
     * @mbg.generated
     */
    public Long getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.ctype
     *
     * @param ctype the value for ss_module.ctype
     *
     * @mbg.generated
     */
    public void setCtype(Long ctype) {
        this.ctype = ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.state
     *
     * @return the value of ss_module.state
     *
     * @mbg.generated
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.state
     *
     * @param state the value for ss_module.state
     *
     * @mbg.generated
     */
    public void setState(Long state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.belong
     *
     * @return the value of ss_module.belong
     *
     * @mbg.generated
     */
    public String getBelong() {
        return belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.belong
     *
     * @param belong the value for ss_module.belong
     *
     * @mbg.generated
     */
    public void setBelong(String belong) {
        this.belong = belong == null ? null : belong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.cwhich
     *
     * @return the value of ss_module.cwhich
     *
     * @mbg.generated
     */
    public String getCwhich() {
        return cwhich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.cwhich
     *
     * @param cwhich the value for ss_module.cwhich
     *
     * @mbg.generated
     */
    public void setCwhich(String cwhich) {
        this.cwhich = cwhich == null ? null : cwhich.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.quote_num
     *
     * @return the value of ss_module.quote_num
     *
     * @mbg.generated
     */
    public Long getQuoteNum() {
        return quoteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.quote_num
     *
     * @param quoteNum the value for ss_module.quote_num
     *
     * @mbg.generated
     */
    public void setQuoteNum(Long quoteNum) {
        this.quoteNum = quoteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.remark
     *
     * @return the value of ss_module.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.remark
     *
     * @param remark the value for ss_module.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.order_no
     *
     * @return the value of ss_module.order_no
     *
     * @mbg.generated
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.order_no
     *
     * @param orderNo the value for ss_module.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }
}