package com.cdx.dao.system;

import com.cdx.domain.system.Module;
import com.cdx.domain.system.ModuleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ModuleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbg.generated
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbg.generated
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbg.generated
     */
    List<Module> selectByExample(ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbg.generated
     */
    Module selectByPrimaryKey(String moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Module record);

    // 查询指定角色拥有的模块信息
    List<Module> findByRid(String id);

    // 删除角色的所有权限
    void deleteToRole(String rid);

    // 添加角色的权限信息
    void insertToRole(@Param("rid") String rid,@Param("mid") String moduleId);

    // 查询用户的模块信息
    List<Module> findByUser(String id);

    // 根据belong查询模块信息
    List<Module> findByBelong(String s);
}